export const seedSemillero = [
  { id: 1, nombre: "Semillero Alpha", estado: true },
  { id: 2, nombre: "Semillero Beta", estado: false },
  { id: 3, nombre: "Semillero Gamma", estado: true },
  { id: 4, nombre: "Semillero Delta", estado: false },
  { id: 5, nombre: "Semillero Épsilon", estado: true },
  { id: 6, nombre: "Semillero Omega", estado: false },
  { id: 7, nombre: "Semillero Ciencia Viva", estado: true },
  { id: 8, nombre: "Semillero Innovadores", estado: false },
  { id: 9, nombre: "Semillero Creativo", estado: true },
  { id: 10, nombre: "Semillero Matemático", estado: false },
  { id: 11, nombre: "Semillero Ambiental", estado: true },
  { id: 12, nombre: "Semillero TIC", estado: false },
  { id: 13, nombre: "Semillero Neurociencia", estado: true },
  { id: 14, nombre: "Semillero Literario", estado: false },
  { id: 15, nombre: "Semillero Jurídico", estado: true },
  { id: 16, nombre: "Semillero de Paz", estado: false },
  { id: 17, nombre: "Semillero Empresarial", estado: true },
  { id: 18, nombre: "Semillero BioTech", estado: false },
  { id: 19, nombre: "Semillero Robótica", estado: true },
  { id: 20, nombre: "Semillero Humanista", estado: false },
  { id: 21, nombre: "Semillero de Datos", estado: true },
  { id: 22, nombre: "Semillero AgroTech", estado: false },
];
