export const seedEstudiantes = [
  {
    id: 1,
    identificacion: "10001",
    nombre: "Ana Pérez",
    email: "ana@example.com",
  },
  {
    id: 2,
    identificacion: "10002",
    nombre: "Juan Torres",
    email: "juan@example.com",
  },
  {
    id: 3,
    identificacion: "10003",
    nombre: "Laura Mendoza",
    email: "laura.mendoza@example.com",
  },
  {
    id: 4,
    identificacion: "10004",
    nombre: "Carlos García",
    email: "carlos.garcia@example.com",
  },
  {
    id: 5,
    identificacion: "10005",
    nombre: "Valeria Ruiz",
    email: "valeria.ruiz@example.com",
  },
  {
    id: 6,
    identificacion: "10006",
    nombre: "Mateo Rodríguez",
    email: "mateo.rodriguez@example.com",
  },
  {
    id: 7,
    identificacion: "10007",
    nombre: "Sofía Herrera",
    email: "sofia.herrera@example.com",
  },
  {
    id: 8,
    identificacion: "10008",
    nombre: "Tomás Vargas",
    email: "tomas.vargas@example.com",
  },
  {
    id: 9,
    identificacion: "10009",
    nombre: "Daniela Ríos",
    email: "daniela.rios@example.com",
  },
  {
    id: 10,
    identificacion: "10010",
    nombre: "Sebastián Gómez",
    email: "sebastian.gomez@example.com",
  },
  {
    id: 11,
    identificacion: "10011",
    nombre: "Camila Navarro",
    email: "camila.navarro@example.com",
  },
  {
    id: 12,
    identificacion: "10012",
    nombre: "Emilio Sánchez",
    email: "emilio.sanchez@example.com",
  },
  {
    id: 13,
    identificacion: "10013",
    nombre: "Isabella Castro",
    email: "isabella.castro@example.com",
  },
  {
    id: 14,
    identificacion: "10014",
    nombre: "Lucas Peña",
    email: "lucas.pena@example.com",
  },
  {
    id: 15,
    identificacion: "10015",
    nombre: "Martina Cárdenas",
    email: "martina.cardenas@example.com",
  },
  {
    id: 16,
    identificacion: "10016",
    nombre: "Andrés Romero",
    email: "andres.romero@example.com",
  },
  {
    id: 17,
    identificacion: "10017",
    nombre: "Juliana Álvarez",
    email: "juliana.alvarez@example.com",
  },
  {
    id: 18,
    identificacion: "10018",
    nombre: "Esteban León",
    email: "esteban.leon@example.com",
  },
  {
    id: 19,
    identificacion: "10019",
    nombre: "Natalia Bravo",
    email: "natalia.bravo@example.com",
  },
  {
    id: 20,
    identificacion: "10020",
    nombre: "Iván Silva",
    email: "ivan.silva@example.com",
  },
  {
    id: 21,
    identificacion: "10021",
    nombre: "Luciana Torres",
    email: "luciana.torres@example.com",
  },
  {
    id: 22,
    identificacion: "10022",
    nombre: "Felipe Moreno",
    email: "felipe.moreno@example.com",
  },
];
