export const seedFaseProyecto = [
  { id: 1, nombre: "Fase 1", estado: true },
  { id: 2, nombre: "Fase Final", estado: false },
  { id: 3, nombre: "Fase Inicial", estado: true },
  { id: 4, nombre: "Fase de Planeación", estado: false },
  { id: 5, nombre: "Fase de Ejecución", estado: true },
  { id: 6, nombre: "Fase de Evaluación", estado: false },
  { id: 7, nombre: "Fase de Diseño", estado: true },
  { id: 8, nombre: "Fase de Investigación", estado: false },
  { id: 9, nombre: "Fase de Desarrollo", estado: true },
  { id: 10, nombre: "Fase de Validación", estado: false },
  { id: 11, nombre: "Fase de Pruebas", estado: true },
  { id: 12, nombre: "Fase de Implementación", estado: false },
  { id: 13, nombre: "Fase de Seguimiento", estado: true },
  { id: 14, nombre: "Fase de Consolidación", estado: false },
  { id: 15, nombre: "Fase de Cierre", estado: true },
  { id: 16, nombre: "Fase de Ajuste", estado: false },
  { id: 17, nombre: "Fase Técnica", estado: true },
  { id: 18, nombre: "Fase Administrativa", estado: false },
  { id: 19, nombre: "Fase Académica", estado: true },
  { id: 20, nombre: "Fase de Aprobación", estado: false },
  { id: 21, nombre: "Fase de Publicación", estado: true },
  { id: 22, nombre: "Fase de Retroalimentación", estado: false },
];
