export const seedHistorialDocumento = [
  { id: 1, version: "v1.0", proyecto: 1, estado: true },
  { id: 2, version: "v1.1", proyecto: 2, estado: false },
  { id: 3, version: "v1.2", proyecto: 1, estado: true },
  { id: 4, version: "v2.0", proyecto: 3, estado: false },
  { id: 5, version: "v2.1", proyecto: 2, estado: true },
  { id: 6, version: "v3.0", proyecto: 4, estado: false },
  { id: 7, version: "v3.1", proyecto: 3, estado: true },
  { id: 8, version: "v3.2", proyecto: 1, estado: false },
  { id: 9, version: "v4.0", proyecto: 5, estado: true },
  { id: 10, version: "v4.1", proyecto: 6, estado: false },
  { id: 11, version: "v4.2", proyecto: 2, estado: true },
  { id: 12, version: "v5.0", proyecto: 7, estado: false },
  { id: 13, version: "v5.1", proyecto: 4, estado: true },
  { id: 14, version: "v5.2", proyecto: 5, estado: false },
  { id: 15, version: "v6.0", proyecto: 8, estado: true },
  { id: 16, version: "v6.1", proyecto: 9, estado: false },
  { id: 17, version: "v6.2", proyecto: 6, estado: true },
  { id: 18, version: "v7.0", proyecto: 10, estado: false },
  { id: 19, version: "v7.1", proyecto: 3, estado: true },
  { id: 20, version: "v7.2", proyecto: 1, estado: false },
  { id: 21, version: "v8.0", proyecto: 8, estado: true },
  { id: 22, version: "v8.1", proyecto: 9, estado: false },
];
