export const seedProyecto = [
  {
    id: 1,
    nombre: "Proyecto A",
    version: "1.0",
    fechaInscripcion: "2024-01-10T10:00",
    numeroIntegrantes: 3,
    convocatoria: 1,
    semillero: 1,
    faseProyecto: 1,
    sede: 1,
    programaAcademico: 1,
    facultad: 1,
    area: 1,
    estado: true,
  },
  {
    id: 2,
    nombre: "Proyecto B",
    version: "1.0",
    fechaInscripcion: "2024-01-15T10:00",
    numeroIntegrantes: 4,
    convocatoria: 2,
    semillero: 2,
    faseProyecto: 2,
    sede: 2,
    programaAcademico: 2,
    facultad: 2,
    area: 2,
    estado: false,
  },
  {
    id: 3,
    nombre: "Proyecto C",
    version: "1.1",
    fechaInscripcion: "2024-02-01T09:30",
    numeroIntegrantes: 5,
    convocatoria: 1,
    semillero: 3,
    faseProyecto: 3,
    sede: 3,
    programaAcademico: 3,
    facultad: 3,
    area: 3,
    estado: true,
  },
  {
    id: 4,
    nombre: "Proyecto D",
    version: "1.0",
    fechaInscripcion: "2024-02-05T11:00",
    numeroIntegrantes: 2,
    convocatoria: 2,
    semillero: 1,
    faseProyecto: 2,
    sede: 1,
    programaAcademico: 4,
    facultad: 4,
    area: 1,
    estado: false,
  },
  {
    id: 5,
    nombre: "Proyecto E",
    version: "1.2",
    fechaInscripcion: "2024-02-10T08:00",
    numeroIntegrantes: 3,
    convocatoria: 1,
    semillero: 2,
    faseProyecto: 1,
    sede: 2,
    programaAcademico: 1,
    facultad: 1,
    area: 2,
    estado: true,
  },
  {
    id: 6,
    nombre: "Proyecto F",
    version: "2.0",
    fechaInscripcion: "2024-02-15T10:45",
    numeroIntegrantes: 6,
    convocatoria: 2,
    semillero: 4,
    faseProyecto: 3,
    sede: 3,
    programaAcademico: 5,
    facultad: 5,
    area: 5,
    estado: false,
  },
  {
    id: 7,
    nombre: "Proyecto G",
    version: "1.0",
    fechaInscripcion: "2024-02-20T14:00",
    numeroIntegrantes: 4,
    convocatoria: 1,
    semillero: 5,
    faseProyecto: 2,
    sede: 2,
    programaAcademico: 6,
    facultad: 2,
    area: 2,
    estado: true,
  },
  {
    id: 8,
    nombre: "Proyecto H",
    version: "1.3",
    fechaInscripcion: "2024-02-25T09:00",
    numeroIntegrantes: 5,
    convocatoria: 2,
    semillero: 3,
    faseProyecto: 3,
    sede: 1,
    programaAcademico: 7,
    facultad: 3,
    area: 1,
    estado: false,
  },
  {
    id: 9,
    nombre: "Proyecto I",
    version: "2.1",
    fechaInscripcion: "2024-03-01T10:15",
    numeroIntegrantes: 3,
    convocatoria: 1,
    semillero: 6,
    faseProyecto: 2,
    sede: 2,
    programaAcademico: 8,
    facultad: 4,
    area: 4,
    estado: true,
  },
  {
    id: 10,
    nombre: "Proyecto J",
    version: "1.0",
    fechaInscripcion: "2024-03-05T13:00",
    numeroIntegrantes: 2,
    convocatoria: 2,
    semillero: 2,
    faseProyecto: 1,
    sede: 3,
    programaAcademico: 9,
    facultad: 5,
    area: 5,
    estado: false,
  },
  {
    id: 11,
    nombre: "Proyecto K",
    version: "1.1",
    fechaInscripcion: "2024-03-10T09:30",
    numeroIntegrantes: 4,
    convocatoria: 1,
    semillero: 1,
    faseProyecto: 3,
    sede: 1,
    programaAcademico: 10,
    facultad: 1,
    area: 1,
    estado: true,
  },
  {
    id: 12,
    nombre: "Proyecto L",
    version: "2.0",
    fechaInscripcion: "2024-03-15T10:00",
    numeroIntegrantes: 3,
    convocatoria: 2,
    semillero: 5,
    faseProyecto: 2,
    sede: 2,
    programaAcademico: 2,
    facultad: 2,
    area: 3,
    estado: false,
  },
  {
    id: 13,
    nombre: "Proyecto M",
    version: "1.4",
    fechaInscripcion: "2024-03-20T08:30",
    numeroIntegrantes: 5,
    convocatoria: 1,
    semillero: 3,
    faseProyecto: 1,
    sede: 3,
    programaAcademico: 4,
    facultad: 4,
    area: 4,
    estado: true,
  },
  {
    id: 14,
    nombre: "Proyecto N",
    version: "2.1",
    fechaInscripcion: "2024-03-25T10:00",
    numeroIntegrantes: 4,
    convocatoria: 2,
    semillero: 6,
    faseProyecto: 2,
    sede: 1,
    programaAcademico: 6,
    facultad: 1,
    area: 2,
    estado: false,
  },
  {
    id: 15,
    nombre: "Proyecto O",
    version: "1.0",
    fechaInscripcion: "2024-03-30T09:00",
    numeroIntegrantes: 2,
    convocatoria: 1,
    semillero: 1,
    faseProyecto: 3,
    sede: 2,
    programaAcademico: 8,
    facultad: 3,
    area: 3,
    estado: true,
  },
  {
    id: 16,
    nombre: "Proyecto P",
    version: "1.2",
    fechaInscripcion: "2024-04-01T14:30",
    numeroIntegrantes: 3,
    convocatoria: 2,
    semillero: 4,
    faseProyecto: 1,
    sede: 3,
    programaAcademico: 5,
    facultad: 2,
    area: 1,
    estado: false,
  },
  {
    id: 17,
    nombre: "Proyecto Q",
    version: "2.0",
    fechaInscripcion: "2024-04-05T10:00",
    numeroIntegrantes: 4,
    convocatoria: 1,
    semillero: 2,
    faseProyecto: 2,
    sede: 1,
    programaAcademico: 3,
    facultad: 1,
    area: 4,
    estado: true,
  },
  {
    id: 18,
    nombre: "Proyecto R",
    version: "1.1",
    fechaInscripcion: "2024-04-10T08:00",
    numeroIntegrantes: 5,
    convocatoria: 2,
    semillero: 3,
    faseProyecto: 3,
    sede: 2,
    programaAcademico: 7,
    facultad: 2,
    area: 2,
    estado: false,
  },
  {
    id: 19,
    nombre: "Proyecto S",
    version: "2.2",
    fechaInscripcion: "2024-04-15T09:45",
    numeroIntegrantes: 4,
    convocatoria: 1,
    semillero: 5,
    faseProyecto: 1,
    sede: 3,
    programaAcademico: 1,
    facultad: 4,
    area: 1,
    estado: true,
  },
  {
    id: 20,
    nombre: "Proyecto T",
    version: "3.0",
    fechaInscripcion: "2024-04-20T10:30",
    numeroIntegrantes: 6,
    convocatoria: 2,
    semillero: 6,
    faseProyecto: 2,
    sede: 2,
    programaAcademico: 9,
    facultad: 5,
    area: 5,
    estado: false,
  },
  {
    id: 21,
    nombre: "Proyecto U",
    version: "1.0",
    fechaInscripcion: "2024-04-25T11:00",
    numeroIntegrantes: 3,
    convocatoria: 1,
    semillero: 1,
    faseProyecto: 3,
    sede: 1,
    programaAcademico: 6,
    facultad: 3,
    area: 3,
    estado: true,
  },
  {
    id: 22,
    nombre: "Proyecto V",
    version: "1.1",
    fechaInscripcion: "2024-04-30T09:00",
    numeroIntegrantes: 2,
    convocatoria: 2,
    semillero: 4,
    faseProyecto: 2,
    sede: 2,
    programaAcademico: 2,
    facultad: 2,
    area: 2,
    estado: false,
  },
];
