export const seedProgramaAcademico = [
  { id: 1, nombre: "Ingeniería de Sistemas", estado: true },
  { id: 2, nombre: "Administración", estado: false },
  { id: 3, nombre: "Ingeniería Industrial", estado: true },
  { id: 4, nombre: "Psicología", estado: false },
  { id: 5, nombre: "Contaduría Pública", estado: true },
  { id: 6, nombre: "Derecho", estado: false },
  { id: 7, nombre: "Comunicación Social", estado: true },
  { id: 8, nombre: "Economía", estado: false },
  { id: 9, nombre: "Mercadeo", estado: true },
  { id: 10, nombre: "Ingeniería Civil", estado: false },
  { id: 11, nombre: "Arquitectura", estado: true },
  { id: 12, nombre: "Trabajo Social", estado: false },
  { id: 13, nombre: "Enfermería", estado: true },
  { id: 14, nombre: "Medicina", estado: false },
  { id: 15, nombre: "Ingeniería Electrónica", estado: true },
  { id: 16, nombre: "Biología", estado: false },
  { id: 17, nombre: "Filosofía", estado: true },
  { id: 18, nombre: "Matemáticas", estado: false },
  { id: 19, nombre: "Lenguas Modernas", estado: true },
  { id: 20, nombre: "Antropología", estado: false },
  { id: 21, nombre: "Artes Visuales", estado: true },
  { id: 22, nombre: "Ciencias Políticas", estado: false },
];
