export const seedProyectoAsesor = [
  { id: 1, proyecto: 1, asesor: 1, estado: true },
  { id: 2, proyecto: 1, asesor: 2, estado: false },
  { id: 3, proyecto: 2, asesor: 3, estado: true },
  { id: 4, proyecto: 2, asesor: 4, estado: false },
  { id: 5, proyecto: 3, asesor: 5, estado: true },
  { id: 6, proyecto: 3, asesor: 6, estado: false },
  { id: 7, proyecto: 4, asesor: 7, estado: true },
  { id: 8, proyecto: 4, asesor: 8, estado: false },
  { id: 9, proyecto: 5, asesor: 9, estado: true },
  { id: 10, proyecto: 5, asesor: 10, estado: false },
  { id: 11, proyecto: 6, asesor: 11, estado: true },
  { id: 12, proyecto: 6, asesor: 12, estado: false },
  { id: 13, proyecto: 7, asesor: 13, estado: true },
  { id: 14, proyecto: 7, asesor: 14, estado: false },
  { id: 15, proyecto: 8, asesor: 15, estado: true },
  { id: 16, proyecto: 8, asesor: 16, estado: false },
  { id: 17, proyecto: 9, asesor: 17, estado: true },
  { id: 18, proyecto: 9, asesor: 18, estado: false },
  { id: 19, proyecto: 10, asesor: 19, estado: true },
  { id: 20, proyecto: 10, asesor: 20, estado: false },
  { id: 21, proyecto: 11, asesor: 21, estado: true },
  { id: 22, proyecto: 11, asesor: 22, estado: false },
];
