export const areasMock = [
  { id: 1, nombre: "Ingeniería", estado: true },
  { id: 2, nombre: "Ciencias Económicas", estado: false },
  { id: 3, nombre: "Salud", estado: true },
  { id: 4, nombre: "Arquitectura", estado: true },
  { id: 5, nombre: "Derecho", estado: false },
  { id: 6, nombre: "Educación", estado: true },
  { id: 7, nombre: "Psicología", estado: false },
  { id: 8, nombre: "Contaduría", estado: true },
  { id: 9, nombre: "Administración", estado: true },
  { id: 10, nombre: "Diseño Gráfico", estado: false },
  { id: 11, nombre: "Ciencias Sociales", estado: true },
  { id: 12, nombre: "Matemáticas", estado: true },
  { id: 13, nombre: "Física", estado: false },
  { id: 14, nombre: "Química", estado: true },
  { id: 15, nombre: "Biología", estado: false },
  { id: 16, nombre: "Medicina", estado: true },
  { id: 17, nombre: "Veterinaria", estado: true },
  { id: 18, nombre: "Ingeniería Industrial", estado: false },
  { id: 19, nombre: "Sistemas", estado: true },
  { id: 20, nombre: "Electrónica", estado: false },
  { id: 21, nombre: "Mecánica", estado: true },
  { id: 22, nombre: "Gastronomía", estado: false },
  { id: 23, nombre: "Turismo", estado: true },
];
