export const convocatoriasMock = [
  { id: 1, nombre: "Convocatoria 2024-1", estado: true },
  { id: 2, nombre: "Convocatoria Especial", estado: false },
  { id: 3, nombre: "Convocatoria Innovación", estado: true },
  { id: 4, nombre: "Convocatoria Investigación", estado: false },
  { id: 5, nombre: "Convocatoria TIC 2024", estado: true },
  { id: 6, nombre: "Convocatoria Salud", estado: false },
  { id: 7, nombre: "Convocatoria Ingenierías", estado: true },
  { id: 8, nombre: "Convocatoria Educación", estado: false },
  { id: 9, nombre: "Convocatoria Semilleros", estado: true },
  { id: 10, nombre: "Convocatoria Ambiental", estado: false },
  { id: 11, nombre: "Convocatoria Emprendimiento", estado: true },
  { id: 12, nombre: "Convocatoria Rural", estado: false },
  { id: 13, nombre: "Convocatoria Urbana", estado: true },
  { id: 14, nombre: "Convocatoria Docencia", estado: false },
  { id: 15, nombre: "Convocatoria Bienestar", estado: true },
  { id: 16, nombre: "Convocatoria Talento Joven", estado: false },
  { id: 17, nombre: "Convocatoria Ciencia Abierta", estado: true },
  { id: 18, nombre: "Convocatoria Multidisciplinaria", estado: false },
  { id: 19, nombre: "Convocatoria Nacional", estado: true },
  { id: 20, nombre: "Convocatoria Internacional", estado: false },
  { id: 21, nombre: "Convocatoria Nuevas Tecnologías", estado: true },
  { id: 22, nombre: "Convocatoria Patrimonio", estado: false },
];
