export const seedProyectoEstudiante = [
  { id: 1, proyecto: 1, estudiante: 1, estado: true },
  { id: 2, proyecto: 1, estudiante: 2, estado: false },
  { id: 3, proyecto: 2, estudiante: 3, estado: true },
  { id: 4, proyecto: 2, estudiante: 4, estado: false },
  { id: 5, proyecto: 3, estudiante: 5, estado: true },
  { id: 6, proyecto: 3, estudiante: 6, estado: false },
  { id: 7, proyecto: 4, estudiante: 7, estado: true },
  { id: 8, proyecto: 4, estudiante: 8, estado: false },
  { id: 9, proyecto: 5, estudiante: 9, estado: true },
  { id: 10, proyecto: 5, estudiante: 10, estado: false },
  { id: 11, proyecto: 6, estudiante: 11, estado: true },
  { id: 12, proyecto: 6, estudiante: 12, estado: false },
  { id: 13, proyecto: 7, estudiante: 13, estado: true },
  { id: 14, proyecto: 7, estudiante: 14, estado: false },
  { id: 15, proyecto: 8, estudiante: 15, estado: true },
  { id: 16, proyecto: 8, estudiante: 16, estado: false },
  { id: 17, proyecto: 9, estudiante: 17, estado: true },
  { id: 18, proyecto: 9, estudiante: 18, estado: false },
  { id: 19, proyecto: 10, estudiante: 19, estado: true },
  { id: 20, proyecto: 10, estudiante: 20, estado: false },
  { id: 21, proyecto: 11, estudiante: 21, estado: true },
  { id: 22, proyecto: 11, estudiante: 22, estado: false },
];
