export const asesorMock = [
  {
    id: 1,
    identificacion: "10001",
    nombre: "Pepito Pérez",
    email: "pepito@outlook.com",
  },
  {
    id: 2,
    identificacion: "10002",
    nombre: "Laura Gómez",
    email: "laura.gomez@example.com",
  },
  {
    id: 3,
    identificacion: "10003",
    nombre: "Carlos Ruiz",
    email: "carlos.ruiz@example.com",
  },
  {
    id: 4,
    identificacion: "10004",
    nombre: "Ana Torres",
    email: "ana.torres@example.com",
  },
  {
    id: 5,
    identificacion: "10005",
    nombre: "Juan Díaz",
    email: "juan.diaz@example.com",
  },
  {
    id: 6,
    identificacion: "10006",
    nombre: "María López",
    email: "maria.lopez@example.com",
  },
  {
    id: 7,
    identificacion: "10007",
    nombre: "José Martínez",
    email: "jose.martinez@example.com",
  },
  {
    id: 8,
    identificacion: "10008",
    nombre: "Camila Herrera",
    email: "camila.herrera@example.com",
  },
  {
    id: 9,
    identificacion: "10009",
    nombre: "Pedro Andrade",
    email: "pedro.andrade@example.com",
  },
  {
    id: 10,
    identificacion: "10010",
    nombre: "Lucía Vargas",
    email: "lucia.vargas@example.com",
  },
  {
    id: 11,
    identificacion: "10011",
    nombre: "Julián Romero",
    email: "julian.romero@example.com",
  },
  {
    id: 12,
    identificacion: "10012",
    nombre: "Daniela Cárdenas",
    email: "daniela.cardenas@example.com",
  },
  {
    id: 13,
    identificacion: "10013",
    nombre: "Andrés Valderrama",
    email: "andres.valderrama@example.com",
  },
  {
    id: 14,
    identificacion: "10014",
    nombre: "Paula Medina",
    email: "paula.medina@example.com",
  },
  {
    id: 15,
    identificacion: "10015",
    nombre: "Felipe García",
    email: "felipe.garcia@example.com",
  },
  {
    id: 16,
    identificacion: "10016",
    nombre: "Valentina Acosta",
    email: "valentina.acosta@example.com",
  },
  {
    id: 17,
    identificacion: "10017",
    nombre: "Esteban Nieto",
    email: "esteban.nieto@example.com",
  },
  {
    id: 18,
    identificacion: "10018",
    nombre: "Isabela Ríos",
    email: "isabela.rios@example.com",
  },
  {
    id: 19,
    identificacion: "10019",
    nombre: "Tomás León",
    email: "tomas.leon@example.com",
  },
  {
    id: 20,
    identificacion: "10020",
    nombre: "Sofía Bermúdez",
    email: "sofia.bermudez@example.com",
  },
];
