export const seedSede = [
  { id: 1, nombre: "Sede Central", estado: true },
  { id: 2, nombre: "Sede Norte", estado: false },
  { id: 3, nombre: "Sede Sur", estado: true },
  { id: 4, nombre: "Sede Oriente", estado: false },
  { id: 5, nombre: "Sede Occidente", estado: true },
  { id: 6, nombre: "Sede Principal", estado: false },
  { id: 7, nombre: "Sede Altos del Norte", estado: true },
  { id: 8, nombre: "Sede San Fernando", estado: false },
  { id: 9, nombre: "Sede Universitaria", estado: true },
  { id: 10, nombre: "Sede Experimental", estado: false },
  { id: 11, nombre: "Sede del Caribe", estado: true },
  { id: 12, nombre: "Sede del Pacífico", estado: false },
  { id: 13, nombre: "Sede Amazónica", estado: true },
  { id: 14, nombre: "Sede Andina", estado: false },
  { id: 15, nombre: "Sede Llanos", estado: true },
  { id: 16, nombre: "Sede Internacional", estado: false },
  { id: 17, nombre: "Sede Tecnológica", estado: true },
  { id: 18, nombre: "Sede Urbana", estado: false },
  { id: 19, nombre: "Sede Rural", estado: true },
  { id: 20, nombre: "Sede Innovación", estado: false },
  { id: 21, nombre: "Sede Académica", estado: true },
  { id: 22, nombre: "Sede Creativa", estado: false },
];
