export const facultadesMock = [
  { id: 1, nombre: "Facultad de Ciencias", estado: true },
  { id: 2, nombre: "Facultad de Derecho", estado: false },
  { id: 3, nombre: "Facultad de Ingeniería", estado: true },
  { id: 4, nombre: "Facultad de Arquitectura", estado: false },
  { id: 5, nombre: "Facultad de Medicina", estado: true },
  { id: 6, nombre: "Facultad de Enfermería", estado: false },
  { id: 7, nombre: "Facultad de Odontología", estado: true },
  { id: 8, nombre: "Facultad de Psicología", estado: false },
  { id: 9, nombre: "Facultad de Economía", estado: true },
  { id: 10, nombre: "Facultad de Administración", estado: false },
  { id: 11, nombre: "Facultad de Comunicación", estado: true },
  { id: 12, nombre: "Facultad de Educación", estado: false },
  { id: 13, nombre: "Facultad de Filosofía", estado: true },
  { id: 14, nombre: "Facultad de Ciencias Sociales", estado: false },
  { id: 15, nombre: "Facultad de Ciencias Políticas", estado: true },
  { id: 16, nombre: "Facultad de Ciencias Naturales", estado: false },
  { id: 17, nombre: "Facultad de Matemáticas", estado: true },
  { id: 18, nombre: "Facultad de Física", estado: false },
  { id: 19, nombre: "Facultad de Química", estado: true },
  { id: 20, nombre: "Facultad de Biología", estado: false },
  { id: 21, nombre: "Facultad de Artes", estado: true },
  { id: 22, nombre: "Facultad de Ciencias del Deporte", estado: false },
];
